# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9qvGD5U-PPXoSHx51sWtL6Zf7UZQuib
"""



import gradio as gr
import pickle
import re
import string

# Load the trained sentiment model and vectorizer
with open("sentiment_model.pkl", "rb") as f:
    model = pickle.load(f)

with open("vectorizer.pkl", "rb") as f:
    vectorizer = pickle.load(f)

# Function to clean text
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"\d+", "", text)  # Remove numbers
    text = text.translate(str.maketrans("", "", string.punctuation))  # Remove punctuation
    return text

# Sentiment prediction function
def predict_sentiment(review):
    processed_review = preprocess_text(review)
    transformed_text = vectorizer.transform([processed_review])  # Use the vectorizer
    sentiment = model.predict(transformed_text)[0]  # Predict sentiment
    return "Positive 😊" if sentiment == "positive" else "Negative 😞"

# Gradio UI
iface = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(placeholder="Enter a Sephora skincare review..."),
    outputs="text",
    title="Skincare Sentiment Analysis",
    description="Enter a skincare product review to analyze its sentiment.",
)

# Launch app
iface.launch()